### PR TITLE
Expose node_id which is the entity ID used by v4 github api

### PR DESCRIPTION
**Pull request by AlistairB**
**Issue reference:**
Closes https://github.com/onrock-eng/github-webhooks/issues/27

**Submission Checklist:**
* [x] Have you followed the guidelines in our [Contributing](../../CONTRIBUTING.md) document (for example, is your tree a clean merge)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission build?
* [x] Does your submission pass tests?
* [x] Have you run lints on your code locally prior to submission?
* [x] Have you updated *all* of the cabal/nix infrastructure?
* [x] Is this a breaking change? Have you discussed this?

### CODE REVIEW

**Comment by donkeybonks** [comment]
Do you think that there is a case to suggest that the node_id should be optional ?

**Comment by AlistairB** [comment]
AFAICT, it is always there for certain entities and never there for others. Specifically these entities should always have it https://developer.github.com/v4/interface/node/

`PageBuild` for example is only exposed via v3 api it seems and as such does not have it.

All the example payloads in https://developer.github.com/v3/activity/events/types/ reliably appear to include it for certain entity types, but not for others.

As such I'm inclined to only add it to the entities that should have it and make it mandatory.

**Comment by AlistairB** [comment]
Personally, I like to err on the side of the more restrictive type that _should_ be correct, as it will blow up loudly if the assumption is wrong. However, with the more permissive optional type, it may be mandatory but we will never know. Happy to do whatever though :)

**Comment by AlistairB** [comment]
I made it optional for `HookIssueLabels` which currently has an optional `id`

**Comment by donkeybonks** [comment]
Sounds good

**Comment by AlistairB** [comment]
@donkeybonks this should be good to go. I made some of the label related types to have the optional node_id just in case. The others I am pretty confident will always have it. Let me know if any changes are needed. Thanks!

**Comment by donkeybonks** [comment]
Thanks, I'll review within the next 24hr.

**Comment by donkeybonks** [comment]
Sorry, I'll need another 24hr.

**Comment by AlistairB** [comment]
No worries. No rush!

**Comment by donkeybonks** [comment]
Looks good to me! Thanks.

**Pull request merged**
