### PR TITLE
Fix withText description for CheckRunEventAction

### LINKED ISSUE #33: Intermittent hlint error
**Operating system or device, package version, compiler version:**

**Issue description:**
Somehow, `hlint` is causing an intermittent failure with the following message (perhaps `hlint` was updated recently).
```
Downloading and running hlint...
######################################################################## 100.0%
examples/scotty/src/Main.hs:26:13-109: Warning: Use print

Found:
  liftIO . putStrLn
    $ (show . whIssueCommentBody . evIssueCommentPayload)
        (ev :: IssueCommentEvent)

Perhaps:

  liftIO
    (print
       (whIssueCommentBody . evIssueCommentPayload
          (ev :: IssueCommentEvent)))
```

**Steps to reproduce:**
See this on Travis here: https://travis-ci.org/github/onrock-eng/github-webhooks/jobs/683262402

We should just fix the lint error.

### LINKED ISSUE #34: withText label for decoding HookCheck* is non-specific
It looks like there was a mistake made here - these labels should be made more specific.

For example, they all read `Hook check suite status`.

### PR DESCRIPTION
**Pull request by AlistairB**
**Issue reference:**
Closes #34
Closes #33

**Submission Checklist:**
* [x] Have you followed the guidelines in our [Contributing](../../CONTRIBUTING.md) document (for example, is your tree a clean merge)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission build?
* [x] Does your submission pass tests?
* [x] Have you run lints on your code locally prior to submission?
* [x] Have you updated *all* of the cabal/nix infrastructure?
* [x] Is this a breaking change? Have you discussed this?

### CODE REVIEW

**Comment by AlistairB** [comment]
I don't really understand what the build failures are.

**Comment by donkeybonks** [comment]
It’s not you, some upgrade to hlint added a lint that broke CI.

**Comment by AlistairB** [comment]
Ah I see. I think this should fix it. The failure seems to be complaining that `putStrLn . show` is equivalent to `print`. The latter is preferred.

**Comment by donkeybonks** [comment]
Sweet thanks, you beat me to fixing #33.

**Pull request merged**
