### PR TITLE
HookCommit: add message

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Comment by donkeybonks** [comment]
Thanks,

It looks like this breaks the build because the GitHub payload examples mustn’t include this. Is this field mandatory?

**Comment by domenkozar** [comment]
GitHub documentation doesn't say, but given that git doesn't allow empty commit messages, I'd be surprised it can be null.

**Comment by domenkozar** [comment]
Actually newer versions allow empty messages via `git commit --allow-empty-message -m ''`, but github will send an empty string.

**Comment by domenkozar** [comment]
Fixing tests.

**Comment by domenkozar** [comment]
I've fixed the pushevent test, but statusevent still fails.

I'm a bit confused as the structure is `commit.commit.message`, but Aeson decoding expects `commit.message`?

**Comment by donkeybonks** [comment]
The actual commit has a much larger and more detailed payload.

Hence the message will actually be in `commit.commit.message`, yes. See here: https://developer.github.com/v3/repos/commits/

Really, the whole `commit.commit` payload should be supported. Will need to make a completely new datatype for that.

**Comment by donkeybonks** [comment]
It would be best to get a real payload too because the GitHub documentation doesn't seem very complete ... `commits: [ ], ...`

**Comment by domenkozar** [comment]
I guess I'm confused how getting `commit.commit.author` works while `commit.commit.message` doesn't work for `StatusEvent`

**Comment by donkeybonks** [comment]
Looks like `StatusEvent` has a thin wrapper around with `sha` and `node_id`, see here:
https://developer.github.com/v3/activity/events/types/#statusevent

But also note there are two entries for `author` and such - there is `commit.author` which is the one we currently parse, and there is also `commit.commit.author` which is an abbreviated version at the same level as the `message` you are trying to parse.

See here:
https://github.com/onrock-eng/github-webhooks/blob/2ad9fab584a8e24f28999ca01bdd866009554682/fixtures/status-event.json#L33

**Comment by domenkozar** [comment]
Thanks! I've pushed a version that is easier to understand, covers both cases and passes tests.

**Comment by donkeybonks** [comment]
I think you'll have to wrap it in another ADT because honestly doing this sort of thing doesn't really seem correct.

The idea of static typing is to prevent invalid states, but now you can accidentally an invalid state if one of your remote payloads is malformed and has two levels i.e. `commit.commit` when it shouldn't.

**Comment by donkeybonks** [comment]
Or if you want a quick and dirty (but reasonable) fix, you can just add a little code inline to `StatusEvent` serialization to read into the extra level of `commit`.

**Comment by domenkozar** [comment]
That would change the contents since sinner commit has less data (e.g. author) for eventstatus.

**Comment by domenkozar** [comment]
>  but now you can accidentally an invalid state if one of your remote payloads is malformed and has two levels i.e. commit.commit when it shouldn't.

Is that hypothetical, or do you see this case can happen in existing github api?

**Comment by donkeybonks** [comment]
I am still thinking about this.

> Is that hypothetical, or do you see this case can happen in existing github api?
It is hypothetical, but we don't make the assumption that this library is used only for interfacing with GitHub. There are a lot of forks by quite a few big core Haskell companies and to be honest I haven't much of an idea how they actually use it.

**Comment by domenkozar** [comment]
I could change the logic to parse the `commit.commit` and fallback to parsing top-level.

I think that's better anyway, because you either parse one structure or the other, not a mix.

**Comment by donkeybonks** [comment]
It should be impossible to parse ‘commit.commit’ unless it’s expected in the payload.

ie
‘StatusEvent’ should always parse it and not accept the payload if it is missing.
‘PushEvent’ should never parse it.

**Pull request closed without merging**
