### PR TITLE
fix(test): Fix read of UTCTime by adding a timezone character at the end

### LINKED ISSUE #29: Get this package back into Stackage
There's a problem in a recent update to aeson with the date parsing that causes the test suite to fail (even though there isn't a noticeable regression).

We'd be very grateful if anyone wanted to undertake this project.

### PR DESCRIPTION
**Pull request by Sir4ur0n**
Closes #29

**Issue reference:**

**Submission Checklist:**
* [ ] Have you followed the guidelines in our [Contributing](../../CONTRIBUTING.md) document (for example, is your tree a clean merge)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission build?
* [ ] Does your submission pass tests?
* [ ] Have you run lints on your code locally prior to submission?
* [ ] Have you updated *all* of the cabal/nix infrastructure?
* [ ] Is this a breaking change? Have you discussed this?

### CODE REVIEW

**Comment by donkeybonks** [comment]
Thank you so much for taking a look at this - it looks good to me, but I’ll just want to check compatibility with older GHC later today before we merge this in.

Once again, thanks a lot. Would I be right in saying, then, that it was entirely an issue with the test suite and did not affect functionality?

**Comment by Sir4ur0n** [comment]
> Would I be right in saying, then, that it was entirely an issue with the test suite and did not affect functionality?

As far as I can tell, yes, you are right, it was only a problem of how you build expected data in tests.

We have had Haskell applications in production for months with `time` 1.9.x and we never had any issue with it or Aeson (except a failure in `cron` code because it relied on unsafe `read`, just like in this lib).

Note: I haven't checked your lib, but I truly hope you don't use `read` in the main code 😄

**Comment by donkeybonks** [comment]
Looks good and seems to pass infra, thanks!
I'll add a few stack files for newer LTS and this PR will mean we'll be able to release `0.15.0` with support for Stackage.
Thank you so much for putting this together.

Usually we add contributors to the `package.yaml` and `AUTHORS` files, shall we add your name [and email]?

**Comment by Sir4ur0n** [comment]
Sure (though not my email please 😄 )

**Pull request merged**
