### PR TITLE
Check suite + check run events

### PR DESCRIPTION
**Pull request by AlistairB**
~Very work in progress. I prefer to create the PR early as I work so I can add notes as I go. I'll clean up the git history when I am done.~ Ready for review.

**Notes**

- https://developer.github.com/v3/activity/events/types/#checksuiteevent does not mention a status of `queued`, however this is the status I see in an example event hitting the app I am working on.
- `app` is also [coming through](https://github.com/onrock-eng/github-webhooks/blob/0a3740ce6252dde8318b6f9f360f117a5837bf01/fixtures/check-suite-event.json#L37-L59). I can't find any reference for this so I'm inclined to ignore it for now.

**Issue reference:**
Closes https://github.com/onrock-eng/github-webhooks/issues/25

**Submission Checklist:**
* [x] Have you followed the guidelines in our [Contributing](../../CONTRIBUTING.md) document (for example, is your tree a clean merge)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission build?
* [x] Does your submission pass tests?
* [x] Have you run lints on your code locally prior to submission? I see no lints related to my additions.
* [x] Have you updated *all* of the cabal/nix infrastructure? N/A
* [x] Is this a breaking change? Have you discussed this? Not breaking. Only adding new things
* [x] Add documentation for new types.

### CODE REVIEW

**Comment by donkeybonks** [comment]
Thanks, I'm watching this.

**Comment by AlistairB** [comment]
@donkeybonks I've been going down the path of creating `BlahSimple` data types for where the [event payload](https://github.com/onrock-eng/github-webhooks/blob/0a3740ce6252dde8318b6f9f360f117a5837bf01/fixtures/check-suite-event.json) does not match those already existing. However, it seems that many are subtly different that this feels a bit unwieldy.

Specifically `CheckSuiteEvent` requires different versions of:

- `HookCommit` - The `url` is not included.
- `HookInstallation` - Only the `id` is included.
- `HookPullRequest` - A much smaller set.
- `PullRequestTarget` - User and label not included.
- `HookRepository` - A very simple version.

I can see some similarity between the representation of `CheckSuiteEvent` and `CheckRunEvent`. I think instead I will create `HookChecksPullRequest` and so on instead. Does that sound reasonable?

**Comment by donkeybonks** [comment]
@AlistairB realistically, it seems that the `Simple` variants are super-specific to this payload, so it's probably better to just inline them.

If, really truly, the payloads are close enough to an existing data type that it's unlikely to break anyone's existing code, it's probably fine to change one or two parameters to optional or such.

**Comment by donkeybonks** [comment]
Nevermind the last comment, your latest commit addresses it perfectly.

**Comment by AlistairB** [comment]
@donkeybonks I'm pretty happy with this so far for `CheckSuiteEvent`. I'm going to proceed with adding `CheckRunEvent` (I prefer these in the same PR as check run may require tweaks to the shared checks data types).

Currently the check suite test for GHC 7.8 is failing with `but got: Left "when expecting a Integral, encountered String instead"`. I'm struggling to pinpoint the issue. I don't suppose you have seen these failures on 7.8 before? I'm guessing it is due to a bug in an old version of `aeson`.

**Comment by donkeybonks** [comment]
If the failures are the same or less than the test suite currently (there are currently a few accepted failures), then it is fine. However, as I understand it, there are a few people using this package with `GHC-7.8` in a commercial setting, hence my stubbornness to support and not drop it in a hope that they eventually swap back to HEAD from their fork.

**Comment by AlistairB** [comment]
@donkeybonks No it does appear that it is specifically failing on the `DecodeEvents can decode CheckSuiteEvent` test only for GHC 7.8. No worries, I'll see if I can figure out what it is failing on.

**Comment by AlistairB** [comment]
Hi @donkeybonks , I think this should be good now. Did you want to me to squash it into a single commit?

While I'm here, are you doing haskell in Melbourne? :smile: I'm Melbourne based. Always curious to hear about companies in Melbourne doing haskell.

**Comment by donkeybonks** [comment]
Hi, yes please, squash it and we'll review it all together :)

I actually write firmware for electric trucks at a startup in South Dandenong (https://sea-electric.com), but I don't use Haskell at work. I noticed there's a clothing brand in Brighton that's hiring a senior Haskell technical lead, but unfortunately that's not me!

**Comment by AlistairB** [comment]
Done. Ah fair enough. Best of luck with it. I'm also trying my hand at a Haskell startup.

**Comment by donkeybonks** [comment]
Did you want to add yourself to `AUTHORS`, `package.yaml` and then rebuild the cabal file as well?

**Comment by donkeybonks** [comment]
Or I can merge this and you can do that as a separate PR if you’d like.

**Comment by AlistairB** [comment]
Sure thanks! I pushed as a separate commit. Can squash it with the other commit if you need.

**Comment by donkeybonks** [comment]
Thank you! Merged with pleasure

**Comment by donkeybonks** [comment]
Once I get an opportunity tomorrow evening, I will update the changelog, bump the version and if all goes well and all the CI are still happy, release this to Hackage.

**Pull request merged**
